# Generated by Django 4.2.3 on 2023-07-14 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_notice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 10, 5, 16, 439529)),
        ),
        migrations.AlterField(
            model_name='leaveapply',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 10, 5, 16, 439529)),
        ),
        migrations.AlterField(
            model_name='notice_board',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 10, 5, 16, 439529)),
        ),
        migrations.AlterField(
            model_name='paycheque',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 10, 5, 16, 439529)),
        ),
        migrations.AlterField(
            model_name='paycheque',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 10, 5, 16, 439529)),
        ),
        migrations.AlterField(
            model_name='todaytasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 10, 5, 16, 439529)),
        ),
    ]
