# Generated by Django 4.2.3 on 2023-07-14 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Dashboard", "0002_alter_department_notice_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
        migrations.AlterField(
            model_name="department_notice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 10, 58, 17, 644979)
            ),
        ),
        migrations.AlterField(
            model_name="leaveapply",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 10, 58, 17, 644979)
            ),
        ),
        migrations.AlterField(
            model_name="notice_board",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 10, 58, 17, 640157)
            ),
        ),
        migrations.AlterField(
            model_name="paycheque",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 10, 58, 17, 645497)
            ),
        ),
        migrations.AlterField(
            model_name="paycheque",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 10, 58, 17, 645497)
            ),
        ),
        migrations.AlterField(
            model_name="todaytasks",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 10, 58, 17, 645497)
            ),
        ),
    ]
