# Generated by Django 4.2.3 on 2023-07-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_notice_board_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='notice_board',
            name='image',
        ),
        migrations.AddField(
            model_name='notice_board',
            name='images',
            field=models.ManyToManyField(blank=True, to='Dashboard.photo'),
        ),
    ]
