# Generated by Django 4.2.3 on 2023-07-14 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Dashboard", "0003_remove_userprofile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(default=1, upload_to="userprofile/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="department_notice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 11, 44, 25, 918568)
            ),
        ),
        migrations.AlterField(
            model_name="leaveapply",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 11, 44, 25, 918568)
            ),
        ),
        migrations.AlterField(
            model_name="notice_board",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 11, 44, 25, 918568)
            ),
        ),
        migrations.AlterField(
            model_name="paycheque",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 11, 44, 25, 920049)
            ),
        ),
        migrations.AlterField(
            model_name="paycheque",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 11, 44, 25, 920049)
            ),
        ),
        migrations.AlterField(
            model_name="todaytasks",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 11, 44, 25, 920049)
            ),
        ),
    ]
