# Generated by Django 4.2.3 on 2023-07-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_photo_remove_notice_board_image_notice_board_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice_board',
            name='images',
        ),
        migrations.AddField(
            model_name='notice_board',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
