# Generated by Django 4.2.3 on 2023-07-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_remove_notice_board_images_notice_board_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_board',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='notice_board',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice_board',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
