# Generated by Django 4.2.3 on 2023-07-12 15:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0007_leaveapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_notice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 20, 51, 14, 962545)),
        ),
        migrations.AddField(
            model_name='leaveapply',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 20, 51, 14, 962545)),
        ),
        migrations.AddField(
            model_name='notice_board',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 20, 51, 14, 962545)),
        ),
        migrations.AlterField(
            model_name='leaveapply',
            name='approved_by_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves_hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaveapply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TodayTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 7, 12, 20, 51, 14, 962545))),
                ('department_notice_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.department_notice')),
                ('notice_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.notice_board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paycheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period', models.DateField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incentives_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 7, 12, 20, 51, 14, 962545))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 7, 12, 20, 51, 14, 962545))),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_paycheques', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paycheques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
