# Generated by Django 4.2.3 on 2023-07-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_department_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('TESTING', 'Testing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HR', 'Hr'), ('MANAGER', 'Manager'), ('WORKER', 'Worker')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
