# Generated by Django 4.2.3 on 2023-07-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_code_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=None, max_length=13, null=True, unique=True),
        ),
    ]
