# Generated by Django 4.2.3 on 2023-07-14 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_user_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 14, 11, 57, 2, 779793)
            ),
        ),
    ]
