# Generated by Django 4.2.3 on 2023-07-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_user_is_manager_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_backend",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_frontend",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_hr",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_testing",
            field=models.BooleanField(default=False),
        ),
    ]
