# Generated by Django 4.2.3 on 2023-07-16 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todaytasks",
            name="comment",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="todaytasks",
            name="department_notice_board",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_comment",
                to="employee_dashboard.department_notice",
            ),
        ),
        migrations.AlterField(
            model_name="todaytasks",
            name="notice_board",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notice_board_comment",
                to="employee_dashboard.notice_board",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="income",
            field=models.FloatField(null=True),
        ),
    ]
