# Generated by Django 4.2.3 on 2023-07-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_dashboard", "0002_alter_todaytasks_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapply",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
