# Generated by Django 4.2.3 on 2023-07-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_dashboard", "0003_leaveapply_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paycheque",
            name="gross_salary",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
