# Generated by Django 4.2.3 on 2023-07-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_dashboard", "0005_paycheque_employer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paycheque",
            name="gross_salary",
        ),
        migrations.RemoveField(
            model_name="paycheque",
            name="incentives_bonus",
        ),
        migrations.RemoveField(
            model_name="paycheque",
            name="net_pay",
        ),
        migrations.RemoveField(
            model_name="paycheque",
            name="pay_period",
        ),
        migrations.AddField(
            model_name="paycheque",
            name="allowances",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="paycheque",
            name="base_salary",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paycheque",
            name="bonus",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="paycheque",
            name="overtime_hours",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="paycheque",
            name="overtime_pay_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="paycheque",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="paycheque",
            name="deductions",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
