# Generated by Django 4.2.3 on 2023-07-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_dashboard", "0006_remove_paycheque_gross_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paycheque",
            name="allowances",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="paycheque",
            name="base_salary",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="paycheque",
            name="bonus",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="paycheque",
            name="deductions",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="paycheque",
            name="overtime_pay_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="paycheque",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
    ]
