# Generated by Django 4.2.3 on 2023-07-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_dashboard", "0008_remove_todaytasks_notice_board_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todaytasks",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Completed", "Completed"), ("Pending", "Pending")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
