# Generated by Django 4.2.3 on 2023-07-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_dashboard", "0012_alter_department_notice_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                default="default.profilepicture.jp", upload_to="userprofile/"
            ),
        ),
    ]
